{{- if .Values.canary.enabled }}
apiVersion: flagger.app/v1alpha3
kind: Canary
metadata:
  name: {{ template "podinfo.fullname" . }}
  labels:
    app: {{ template "podinfo.name" . }}
    chart: {{ template "podinfo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if .Values.canary.provider }}
  provider: {{ .Values.canary.provider }}
  {{- end }}
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "podinfo.fullname" . }}
  progressDeadlineSeconds: 60
{{- if .Values.hpa.enabled }}
  autoscalerRef:
    apiVersion: autoscaling/v2beta1
    kind: HorizontalPodAutoscaler
    name: {{ template "podinfo.fullname" . }}
{{- end }}
{{- if .Values.canary.provider }}
  {{- if eq .Values.canary.provider "nginx" }}
  ingressRef:
    apiVersion: extensions/v1beta1
    kind: Ingress
    name: {{ template "podinfo.fullname" . }}
  {{- end }}
{{- end }}
  service:
    port: {{ .Values.service.port }}
    {{- if .Values.canary.istioIngress.enabled }}
    gateways:
    - {{ .Values.canary.istioIngress.gateway }}
    hosts:
    - {{ .Values.canary.istioIngress.host }}
    trafficPolicy:
      tls:
        mode: {{ .Values.canary.istioTLS }}
    {{- end }}
  canaryAnalysis:
    interval: {{ .Values.canary.analysis.interval }}
    threshold: {{ .Values.canary.analysis.threshold }}
    maxWeight: {{ .Values.canary.analysis.maxWeight }}
    stepWeight: {{ .Values.canary.analysis.stepWeight }}
    metrics:
    - name: request-success-rate
      threshold: {{ .Values.canary.thresholds.successRate }}
      interval: 1m
    - name: request-duration
      threshold: {{ .Values.canary.thresholds.latency }}
      interval: 1m
    {{- if or .Values.canary.acceptancetest.enabled .Values.canary.helmtest.enabled .Values.canary.loadtest.enabled }}
    webhooks:
      {{- if .Values.canary.acceptancetest.enabled }}
      - name: "acceptance-test"
        type: pre-rollout
        url: {{ .Values.canary.acceptancetest.url }}
        timeout: 30s
        metadata:
          type: "bash"
          cmd: "curl -sd 'test' http://{{ template "podinfo.fullname" . }}-canary.{{ .Release.Namespace }}:{{ .Values.service.port }}/token | grep token"
      {{- end }}
      {{- if .Values.canary.helmtest.enabled }}
      - name: "helm-test"
        type: pre-rollout
        url: {{ .Values.canary.helmtest.url }}
        timeout: 3m
        metadata:
          type: "helm"
          cmd: "test {{ .Release.Name }} --cleanup"
      {{- end }}
      {{- if .Values.canary.loadtest.enabled }}
      - name: load-test-get
        url: {{ .Values.canary.loadtest.url }}
        timeout: 5s
        metadata:
          cmd: "hey -z 1m -q 5 -c 2 http://{{ template "podinfo.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.service.port }}"
      - name: load-test-post
        url: {{ .Values.canary.loadtest.url }}
        timeout: 5s
        metadata:
          cmd: "hey -z 1m -q 5 -c 2 -m POST -d '{\"test\": true}' http://{{ template "podinfo.fullname" . }}.{{ .Release.Namespace }}:{{ .Values.service.port }}/echo"
      {{- end }}
    {{- end }}
{{- end }}