# Default values for podinfo.
image:
  repository: stefanprodan/podinfo
  tag: 3.1.0
  pullPolicy: IfNotPresent

podAnnotations: {}

service:
  enabled: false
  type: ClusterIP
  port: 9898

grpc:
  port: 9999

metrics:
  port: 9797

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  cpu: 80
  memory: 512Mi

canary:
  enabled: false
  # service mesh provider (optional)
  # can be: kubernetes, istio, linkerd, appmesh, nginx, gloo, supergloo
  provider:
  bluegreen:
    enabled: false
  istioIngress:
    enabled: false
    # Istio ingress gateway name
    gateway: public-gateway.istio-system.svc.cluster.local
    # external host name, e.g. podinfo.example.com
    host:
  # Istio traffic policy TLS mode, either DISABLE or ISTIO_MUTUAL
  istioTLS: DISABLE
  analysis:
    # schedule interval (default 60s)
    interval: 15s
    # max number of failed metric checks before rollback
    threshold: 10
    # max traffic percentage routed to canary
    # percentage (0-100)
    maxWeight: 50
    # canary increment step
    # percentage (0-100)
    stepWeight: 5
    # for blue/green deployments, iterations (interval * iterations is the total analysis duration)
    iterations: 10
  thresholds:
    # minimum req success rate (non 5xx responses)
    # percentage (0-100)
    successRate: 99
    # maximum req duration P99
    # milliseconds
    latency: 500
  webhooks:
    acceptancetest:
      enabled: false
    helmtest:
      enabled: false
    loadtest:
      enabled: false
    manualgate:
      enabled: false
    urls:
      # trailing slash is required
      # helm tester address
      helmtester: http://flagger-helmtester.kube-system/
      # load tester address
      loadtester: http://flagger-loadtester.test/

ingress:
  enabled: false
  annotations: {}
  hostname:
  tls: []

resources:
  limits:
  requests:
    cpu: 100m
    memory: 32Mi

nodeSelector: {}
tolerations: []
affinity: {}

nameOverride: ""
fullnameOverride: ""

logLevel: info
backend: # http://backend-podinfo:9898/echo
backends: []
color: blue
logo:
message: # UI greetings

faults:
  delay: false
  error: false

httpServer:
  timeout: 30s
